# Generated by Django 5.2.7 on 2026-07-01 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_django52_field_updates'),
        ('app', '0051_init_basemaps'),
    ]

    operations = [
    ]
