# Generated by Django 5.2.7 on 2026-07-01 07:27

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_merge_0045_django52_field_updates_0051_init_basemaps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemap',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='plugindatum',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectgroupobjectpermission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectuserobjectpermission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='media',
            field=models.JSONField(blank=True, default=list, help_text='List of media files associated with this task', verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='border',
            field=colorfield.fields.ColorField(default='#e7e7e7', help_text='The color of most borders.', image_field=None, max_length=25, samples=None, verbose_name='Border'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='button_danger',
            field=colorfield.fields.ColorField(default='#e74c3c', help_text='Delete button color.', image_field=None, max_length=25, samples=None, verbose_name='Button Danger'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='button_default',
            field=colorfield.fields.ColorField(default='#95a5a6', help_text='Default button color.', image_field=None, max_length=25, samples=None, verbose_name='Button Default'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='button_primary',
            field=colorfield.fields.ColorField(default='#2c3e50', help_text='Primary button color.', image_field=None, max_length=25, samples=None, verbose_name='Button Primary'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='dialog_warning',
            field=colorfield.fields.ColorField(default='#f39c12', help_text='The border color of warning dialogs.', image_field=None, max_length=25, samples=None, verbose_name='Dialog Warning'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='failed',
            field=colorfield.fields.ColorField(default='#ffcbcb', help_text='The background color of failed notifications.', image_field=None, max_length=25, samples=None, verbose_name='Failed'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='header_background',
            field=colorfield.fields.ColorField(default='#3498db', help_text="Background color of the site's header.", image_field=None, max_length=25, samples=None, verbose_name='Header Background'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='header_primary',
            field=colorfield.fields.ColorField(default='#ffffff', help_text="Text and icons in the site's header.", image_field=None, max_length=25, samples=None, verbose_name='Header Primary'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='highlight',
            field=colorfield.fields.ColorField(default='#f7f7f7', help_text='The background color of panels and some borders.', image_field=None, max_length=25, samples=None, verbose_name='Highlight'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='primary',
            field=colorfield.fields.ColorField(default='#2c3e50', help_text='Most text, icons, and borders.', image_field=None, max_length=25, samples=None, verbose_name='Primary'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secondary',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='The main background color, and text color of some buttons.', image_field=None, max_length=25, samples=None, verbose_name='Secondary'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='success',
            field=colorfield.fields.ColorField(default='#cbffcd', help_text='The background color of success notifications.', image_field=None, max_length=25, samples=None, verbose_name='Success'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='tertiary',
            field=colorfield.fields.ColorField(default='#3498db', help_text='Navigation links.', image_field=None, max_length=25, samples=None, verbose_name='Tertiary'),
        ),
    ]
