# Generated by Django 5.2.7 on 2026-07-01 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodeodm', '0010_django52_jsonfield_update'),
        ('nodeodm', '0010_rename_odm_to_odx'),
    ]

    operations = [
    ]
