name: Test Docker

on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Free disk space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - uses: actions/checkout@v7
      with:
        submodules: 'recursive'
      name: Checkout
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12
    - name: Build and Test
      run: |
        docker system prune -af
        docker volume prune -af
        docker compose -f docker-compose.yml -f docker-compose.build.yml build --build-arg TEST_BUILD=ON
        docker compose -f docker-compose.yml -f docker-compose.build.yml up -d
        sleep 20
        docker compose exec -T webapp /webui/webui.sh test
